#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


# --------------
# Stream edition
# --------------
FROM eclipse-temurin:17-jre-jammy AS builder

# Install dependencies
RUN set -ex; \
  apt-get update; \
  apt-get -y install gpg libsnappy1v5 gettext-base libjemalloc-dev; \
  rm -rf /var/lib/apt/lists/*

# Please copy build-target to the docker dictory first, then copy to the image.
COPY --chown=fluss:fluss fluss-dist/target/fluss-0.8.0-incubating-bin/fluss-0.8.0-incubating /opt/fluss/

 # Prepare environment
ENV FLUSS_HOME=/opt/fluss
ENV PATH=$FLUSS_HOME/bin:$PATH
RUN groupadd --system --gid=9999 fluss && \
     useradd --system --home-dir $FLUSS_HOME --uid=9999 --gid=fluss fluss
WORKDIR $FLUSS_HOME

ENV HADOOP_VERSION=3.3.5
ENV ICEBERG_VERSION=1.9.1
ENV HIVE_VERSION=3.1.3

RUN curl -L https://repo1.maven.org/maven2/io/trino/hadoop/hadoop-apache/${HADOOP_VERSION}-2/hadoop-apache-${HADOOP_VERSION}-2.jar -o plugins/iceberg/hadoop-apache-${HADOOP_VERSION}-2.jar && \
    curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_VERSION}/hadoop-aws-${HADOOP_VERSION}.jar -o plugins/iceberg/hadoop-aws-${HADOOP_VERSION}.jar && \
    curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.316/aws-java-sdk-bundle-1.12.316.jar -o plugins/iceberg/aws-java-sdk-bundle-1.12.316.jar && \
    curl -L https://repo1.maven.org/maven2/org/apache/hive/hive-exec/${HIVE_VERSION}/hive-exec-${HIVE_VERSION}.jar -o plugins/iceberg/hive-exec-${HIVE_VERSION}.jar && \
    curl -L https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar -o plugins/iceberg/commons-logging-1.1.3.jar
#    curl -L https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws/${ICEBERG_VERSION}/iceberg-aws-${ICEBERG_VERSION}.jar -o plugins/iceberg/iceberg-aws-${ICEBERG_VERSION}.jar && \
#    curl -L https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/${ICEBERG_VERSION}/iceberg-aws-bundle-${ICEBERG_VERSION}.jar -o plugins/iceberg/iceberg-aws-bundle-${ICEBERG_VERSION}.jar && \
#    curl -L https://repo1.maven.org/maven2/dev/failsafe/failsafe/3.3.2/failsafe-3.3.2.jar -o plugins/iceberg/failsafe-3.3.2.jar

RUN ["chown", "-R", "fluss:fluss", "."]
COPY docker/fluss/docker-entrypoint.sh /
RUN ["chmod", "+x", "/docker-entrypoint.sh"]
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["help"]
